version: '3'

services:
  mysql:
    image: mysql:8.4.4
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: dbcadmium
      MYSQL_DATABASE: preview
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql-data:/var/lib/mysql

  redis-stack:
    image: redis:7.4.2
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis-data/:/data

  coturn:
    image: coturn/coturn:4.6.3-alpine
    container_name: coturn
    ports:
      - "3478:3478"
      - "5349:5349"
    volumes:
      - ./turnserver.conf:/my/coturn.conf
    command: -c /my/coturn.conf